export const GAME_WIDTH = 100; // percentage
export const GAME_HEIGHT = 100; // percentage
export const PLAYER_SIZE = 12; // same as w-12 in Tailwind
export const ENEMY_SIZE = 8; // same as w-8 in Tailwind
export const MAX_ENEMIES = 20; // Maximum enemies on screen
export const SCORE_INCREMENT = 0.1;
export const BASE_ENEMY_SPEED = 0.5;
export const MIN_ENEMY_SPEED = 1; // Increased minimum speed
export const MAX_ENEMY_SPEED = 3; // Increased maximum speed
export const SPAWN_INTERVAL = 1000; // Spawn every second
export const ENEMIES_PER_SPAWN = 5; // Spawn 5 enemies at once